version: '3.5'

services:
  crdb:
    image: cockroachdb/cockroach
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - crdata:/cockroach/cockroach-data

volumes:
  crdata:
